name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:lunar
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: >-
          apt-get -qqy update

          apt-get -qqy install gcc g++ binutils automake gettext* flex bison intltool libtool git-lfs texinfo build-essential
          autoconf libc-dev linux-libc-dev libmpfr-dev libmpc-dev libisl-dev libgmp-dev libc-dev bc file python3-dev
          libbabeltrace-dev libipt-dev libncurses-dev wget bzip2 autopoint gcc-multilib g++-multilib gawk rsync
      - name: Build
        run: ./build.sh standard x86_64
